module.exports = {
  WEBDRIVERIO_SHADOW_ROOT: '.WatsonAssistantChatHost',
  WEBDRIVERIO_INPUT_ELEMENT: '.WAC__TextArea-textarea',
  WEBDRIVERIO_INPUT_ELEMENT_VISIBLE_TIMEOUT: 30000,
  WEBDRIVERIO_OUTPUT_ELEMENT: '.WAC__bot-message',
  WEBDRIVERIO_IGNOREWELCOMEMESSAGES: 1
}
