module.exports = {
  WEBDRIVERIO_INPUT_ELEMENT: '#WAC__inputContainer-TextArea',
  WEBDRIVERIO_INPUT_ELEMENT_VISIBLE_TIMEOUT: 30000,
  WEBDRIVERIO_OUTPUT_ELEMENT: '.WAC__bot-message',
  WEBDRIVERIO_IGNOREUPFRONTMESSAGES: true
}
